# This Dockerfile was generated by Skelebot
# Editing this file manually is not advised as all changes will be overwritten during Skelebot execution
FROM skelebot/python-base
MAINTAINER Sean Shookman <sshookman@cars.com>
WORKDIR /app
RUN ["pip", "install", "numpy"]
RUN ["pip", "install", "pandas"]
RUN ["pip", "install", "scipy"]
RUN ["pip", "install", "scikit-learn"]
COPY . /app
