name: iris-example
description: Example Skelebot Project
version: '{VERSION}'
skelebotVersion: '{VERSION}'
maintainer: Sean Shookman
contact: sshookman@cars.com
language: Python
ephemeral: False

dependencies: 
- numpy
- pandas
- scipy
- scikit-learn

ignore: 
- '**/*.RData'
- '**/*.csv'
- '**/*.model'
- '**/*.pyc'

jobs: 
- name: loadData
  source: src/loadData.py
  mode: i
  help: Load the Iris Dataset and save it into the data folder for the train job to access
  mapped:
  - data/
- name: train
  source: src/train.py
  mode: i
  help: Use the data loaded in the loadData job to train the iris model
  mapped:
  - models/
  args:
  - name: algorithm
    choices:
    - glm
    - rf
    - xgb
  params:
  - name: name
    alt: n
    default: model
- name: score
  source: src/score.py
  mode: i
  help: Use the model that was built in the train job to score new data against the iris model
  mapped:
  - scored/
  params:
  - name: name
    alt: n
    default: model
  - name: output
    alt: o
    default: scored

components:
  jupyter: 
    port: 8888
    folder: .
  artifactory:
    artifacts: 
    - name: model
      file: models/model.pkl
    url: http://my-artifactory-url.com
    repo: iris-example
    path: models

