components:
  artifactory:
    artifacts:
    - file: models/model.pkl
      name: model
    path: models
    repo: iris-example
    url: http://my-artifactory-url.com
  jupyter:
    folder: .
    port: 8888
contact: sshookman@cars.com
dependencies:
- numpy
- pandas
- scipy
- scikit-learn
description: Example Skelebot Project
ephemeral: false
jobs:
- help: Load the Iris Dataset and save it into the data folder for the train job to
    access
  mappings:
  - data/
  mode: i
  name: loadData
  source: src/loadData.py
- args:
  - choices:
    - glm
    - rf
    - xgb
    name: algorithm
  help: Use the data loaded in the loadData job to train the iris model
  mappings:
  - models/
  mode: i
  name: train
  params:
  - alt: n
    default: model
    name: name
  source: src/train.py
- help: Use the model that was built in the train job to score new data against the
    iris model
  mappings:
  - scored/
  mode: i
  name: score
  params:
  - alt: n
    default: model
    name: name
  - alt: o
    default: scored
    name: output
  source: src/score.py
language: Python
maintainer: Sean Shookman
name: iris-example
skelebotVersion: 0.2.2
version: 1.0.1
