components:
  repository:
    artifactory:
      path: models
      repo: iris-example
      url: http://my-artifactory-url.com
    artifacts:
    - file: models/model.pkl
      name: model
  jupyter:
    folder: .
    port: 8888
contact: sshookman@cars.com
dependencies:
- numpy
- pandas
- scipy
- scikit-learn
description: Example Skelebot Project
ephemeral: false
jobs:
- help: Load the Iris Dataset and save it into the data folder for the train job to
    access
  mappings:
  - data/
  mode: i
  name: loadData
  source: src/loadData.py
- args:
  - choices:
    - glm
    - rf
    - xgb
    name: algorithm
    help: the algorithm to use for modeling (only glm currently supported)
  help: Use the data loaded in the loadData job to train the iris model
  mappings:
  - models/
  mode: i
  name: train
  params:
  - name: things
    alt: t
    accepts: list
    help: Just something to test out a list of things
  - alt: n
    default: model
    name: name
    help: the name of the model object to be saved to the disk
  source: src/train.py
- help: Use the model that was built in the train job to score new data against the
    iris model
  mappings:
  - scored
  mode: i
  name: score
  params:
  - alt: n
    default: model
    name: name
    help: the name of the model object on the disk
  - alt: o
    default: scored
    name: output
    help: the name of the output file to be written
  source: src/score.py
maintainer: Sean Shookman
name: iris-example
