name: skelebot
description: ML Build Tool
maintainer: Sean Shookman
contact: sshookman@cars.com
language: Python
ephemeral: True
primaryJob: test
dependencies:
- PyYAML>=5.1.2
- dohq-artifactory>=0.1.17
- requests>=2.22.0
- schema~=0.7.0
- colorama~=0.4.1
- coverage~=4.5.4
- pytest~=5.1
- boto3~=1.10
- tomli>=1.1.0
ignores:
- '**/*.zip'
- '**/*.pkl'
- '**/*.csv'
- '**/*.model'
- '**/*.pyc'
jobs:
- name: publish
  source: jobs/publish.sh
  mode: i
  help: Build and Publish the Docker Base Images
- name: test
  source: jobs/test.sh
  mode: i
  help: Run the test cases for the project with coverage
  params:
  - name: coverage
    alt: c
    accepts: boolean
    help: Allow for the coverage report to be displayed
  - name: env
    alt: e
    help: ENV
    choices:
    - one
    - two
components:
  jupyter:
    port: 1127
    folder: .
  registry:
    user: skelebot
  contributors:
    repoOwner: carsdotcom
    repoName: skelebot
    files:
    - README.md
  repository:
    s3:
      bucket: my-bucket
      region: us-east-1
      profile: test
    artifacts:
    - name: test1
      file: skelebot.yaml
    - name: test2
      file: skelebot-exp.yaml
      singular: True
