name: skelebot
description: ML Build Tool
version: '{VERSION}'
maintainer: Sean Shookman
contact: sshookman@cars.com
language: Python
ephemeral: False
primaryJob: test
dependencies:
- pyyaml
- artifactory
- coverage
- pytest
ignores: 
- '**/*.zip'
- '**/*.RData'
- '**/*.pkl'
- '**/*.csv'
- '**/*.model'
- '**/*.pyc'
jobs: 
- name: publish
  source: publish.sh
  mode: i
  help: Build, Tag, and Publish the Docker Base Images
  args: 
  - name: version
    help: the version of the base images that are being published to Docker Hub
- name: test
  source: test.sh
  mode: i
  help: Run the test cases for the project with coverage
  params: 
  - name: coverage
    alt: c
    isBoolean: True
    help: Allow for the coverage report to be displayed
components:
  jupyter: 
    port: 1127
    folder: .
