name: skelebot
description: ML Build Tool
maintainer: Sean Shookman
contact: sshookman@cars.com
ephemeral: False
timezone: America/Chicago

dependencies:
  - proj:pyproject.toml

ignores:
- '**/*.zip'
- '**/*.pkl'
- '**/*.csv'
- '**/*.model'
- '**/*.pyc'

primaryJob: test
primaryExe: ENTRYPOINT

jobs:
- name: publish-base
  source: jobs/publish.sh
  mode: i
  help: Build and Publish the Docker Base Images
- name: test
  source: jobs/test.sh
  mode: it
  help: Run the test cases for the project with coverage
  params:
  - name: coverage
    alt: c
    accepts: boolean
    help: Allow for the coverage report to be displayed

components:
  jupyter:
    port: 1127
    folder: .
    lab: True
  registry:
    user: skelebot
  contributors:
    repoOwner: carsdotcom
    repoName: skelebot
    files:
    - README.md
