name: skelebot
description: ML Build Tool
maintainer: Sean Shookman
contact: sshookman@cars.com
ephemeral: True
timezone: America/Chicago

language: Python
dependencies:
- PyYAML>=5.1.2
- artifactory==0.1.17
- requests>=2.22.0
- schema~=0.7.0
- colorama~=0.4.1
- coverage~=4.5.4
- pytest~=5.1
- boto3~=1.10

ignores:
- '**/*.zip'
- '**/*.RData'
- '**/*.pkl'
- '**/*.csv'
- '**/*.model'
- '**/*.pyc'

primaryJob: test
primaryExe: ENTRYPOINT

jobs:
- name: publish-base
  source: jobs/publish.sh
  mode: i
  help: Build and Publish the Docker Base Images
- name: test
  source: jobs/test.sh
  mode: it
  help: Run the test cases for the project with coverage
  params:
  - name: coverage
    alt: c
    accepts: boolean
    help: Allow for the coverage report to be displayed

components:
  jupyter:
    port: 1127
    folder: .
  registry:
    user: skelebot
  contributors:
    repoOwner: carsdotcom
    repoName: skelebot
    files:
    - README.md
