name: skelebot
description: ML Build Tool
version: 0.2.1
skelebotVersion: 0.2.1
maintainer: Sean Shookman
contact: sshookman@cars.com
language: Python
ephemeral: False
primaryJob: test
dependencies:
- pyyaml
- artifactory
- argparse
- coverage
- pytest
ignores: 
- '**/*.zip'
- '**/*.RData'
- '**/*.pkl'
- '**/*.csv'
- '**/*.model'
- '**/*.pyc'
jobs: 
- name: publish
  source: publish.sh
  mode: i
  help: Build, Tag, and Publish the Docker Base Images
  args: 
  - name: version
- name: test
  source: test.sh
  mode: i
  help: Run the test cases for the project with coverage
  params: 
  - name: coverage
    alt: c
    default: n
    choices: 
    - y
    - n
components:
  jupyter: 
    port: 1127
    folder: .
  artifactory:
    artifacts:
    - name: model
      file: models/model.RData
    path: pricing
    repo: cars-ml-core
    url: https://repository.cars.com/artifactory
