name: Publish to Docker Hub

# Trigger the workflow on every release
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-images:
    runs-on: ubuntu-latest
    strategy:
      # Do NOT fail the entire workflow if any docker image fails to build
      fail-fast: false
      matrix:
        image: [python-base,r-base]
        include:
          - dockerfile: ./src/Agent/Dockerfile
            image: ghcr.io/username/image1
          - dockerfile: ./src/Dockerfile-dril4net-distribution
            image: ghcr.io/username/image2
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses:  docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
