name: Publish Skelebot base Docker images

# Run when base-images folder is modified and also allow manual run
on:
  push:
    branches:
      - master
    paths:
      - 'base-images/**'
  schedule:
    # Run automatically at 06:02 on every 1st and 15th day of the month
    - cron:  '2 6 1,15 * *'
  workflow_dispatch:

jobs:
  publish_py:
    name: Publish pure Python base image
    strategy:
      matrix:
        version: ['3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Used to build multi-platform images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: base-images/python-base/${{ matrix.version }}/
          tags: skelebot/python-base:${{ matrix.version }}
          push: true

  # DEPRECATED: Code will be removed in skelebot 3.0
  publish_py_krb:
    name: Publish Python Kerberos base image
    runs-on: ubuntu-latest
    needs: publish_py
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Used to build multi-platform images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Python Kerberos image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: base-images/python-krb/
          tags: skelebot/python-krb
          push: true
